- name: start prometheus
  service:
    name: prometheus
    state: started

- name: stop prometheus
  service:
    name: prometheus
    state: stopped

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: start alertmanager
  service:
    name: alertmanager
    state: started

- name: stop alertmanager
  service:
    name: alertmanager
    state: stopped

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted

- name: start remote_storage_adapter
  service:
    name: remote_storage_adapter
    state: started

- name: stop remote_storage_adapter
  service:
    name: remote_storage_adapter
    state: stopped

- name: restart remote_storage_adapter
  service:
    name: remote_storage_adapter
    state: restarted

- name: reload prometheus
  uri:
    url: http://10.3.10.10:9090/-/reload
    method: POST

- name: reload alertmanager
  uri:
    url: http://10.3.10.10:9093/-/reload
    method: POST
    